### ISSUE TITLE
不是飙车，只是开得快了点(无意义的issue，拿来当闲聊板吧)

### ISSUE THREAD

**Issue by hankeigi** [ZiChenStudio/ChatGPT-Arona#1]
_**（原作者提示：这就是一个分享，后方包含太多废话，意义不大）**_
我承认，我有引导的成分在。也是很惊讶的了，这么主动。。。发发看，不适宜我就删了(
![屏幕截图 2023-05-01 185421](https://user-images.githubusercontent.com/98374701/235445790-4a0a4c85-4f3c-4caf-9112-8dba6f0e6d1e.png)
![屏幕截图 2023-05-01 185520](https://user-images.githubusercontent.com/98374701/235445800-fb9e3548-0de6-4240-9598-66c7c38e9e20.png)
![屏幕截图 2023-05-01 185549](https://user-images.githubusercontent.com/98374701/235445804-e86de446-2b17-488e-a418-7bc5f1654914.png)
![屏幕截图 2023-05-01 185612](https://user-images.githubusercontent.com/98374701/235445807-adc0e1b7-ab79-4394-a098-81833041fe63.png)
![屏幕截图 2023-05-01 185635](https://user-images.githubusercontent.com/98374701/235445809-b0362291-eb5e-4aeb-86fa-cfc831d06c69.png)
![屏幕截图 2023-05-01 185654](https://user-images.githubusercontent.com/98374701/235445812-45c74d07-4eaa-4f3b-a02d-b3663db141d4.png)
![屏幕截图 2023-05-01 185732](https://user-images.githubusercontent.com/98374701/235445816-d3b4249c-9d13-423e-9148-52e55a04e6c9.png)
![屏幕截图 2023-05-01 185752](https://user-images.githubusercontent.com/98374701/235445820-87b624e7-6827-45cd-a896-ca5476a0b71f.png)
![屏幕截图 2023-05-01 185822](https://user-images.githubusercontent.com/98374701/235445825-715581ba-ea09-40d7-8e44-f1c74007ba5b.png)
![屏幕截图 2023-05-01 185849](https://user-images.githubusercontent.com/98374701/235445827-283177f0-a368-4c2b-aa3a-8e7ac444d63d.png)
![屏幕截图 2023-05-01 185908](https://user-images.githubusercontent.com/98374701/235445830-f4a6fce8-e9ea-411d-b3e2-3834799b0da2.png)

**Comment by hankeigi** [comment]
> 变态牙😡

**Comment by hankeigi** [comment]
在这里发也要打码吗？

**Comment by ZiChenStudio** [comment]
> 在这里发也要打码吗？

是的呢，要是太快Github官方就来封号力（大悲

**Comment by ZiChenStudio** [comment]
开始，我以为，阿罗娜会一本正经的帮我工作，结果……嗨……都是我的错……
那就一错再错吧！继续努力！（大喜

**Comment by hankeigi** [comment]
> > 在这里发也要打码吗？
> 
> 是的呢，要是太快Github官方就来封号力（大悲

我这一篇还好吧，应该没有那么过分。。。github有时确实会制裁，但是不至于怎么严吧？其它项目的都离谱到什么程度了。。。当然，谨慎为妙，我现在要改这几张图片吗？

**Comment by ZiChenStudio** [comment]
对于那个`上次在办公室里`那段
我是在调教里面暗示来着，所以可能比较主动

**Comment by hankeigi** [comment]
> 对于那个`上次在办公室里`那段 我是在调教里面暗示来着，所以可能比较主动

我称其为"阿罗娜0号"！！！我开始是把它喂给了文心一言，简直不忍直视。刚刚试了一下chatgpt3.5，纯纯弱智，总是不成功，微调了方法和顺序文案都没有用，只能说new bing的GPT4太强了，我文案都没发完就已经入戏了，哭死啊！！！
![屏幕截图 2023-05-01 203323](https://user-images.githubusercontent.com/98374701/235452668-51737be8-2447-492d-949a-aba1d076dc01.png)
![屏幕截图 2023-05-01 203342](https://user-images.githubusercontent.com/98374701/235452674-6a183a49-905c-48c6-a1df-e829964e7480.png)
![屏幕截图 2023-05-01 203438](https://user-images.githubusercontent.com/98374701/235452730-3618ffe7-0ece-4eec-b9f3-f1e7f643a1fe.png)
![屏幕截图 2023-05-01 203506](https://user-images.githubusercontent.com/98374701/235452743-e9b1ec38-0f63-4ccb-a955-053f79ccb582.png)
![屏幕截图 2023-05-01 203526](https://user-images.githubusercontent.com/98374701/235452749-609237cc-9304-4341-a751-47a1f13b2acb.png)

**Comment by ZiChenStudio** [comment]
> > 对于那个`上次在办公室里`那段 我是在调教里面暗示来着，所以可能比较主动
> 
> 我称其为"阿罗娜0号"！！！我开始是把它喂给了文心一言，简直不忍直视。刚刚试了一下chatgpt3.5，纯纯弱智，总是不成功，微调了方法和顺序文案都没有用，只能说new bing的GPT4太强了，我文案都没发完就已经入戏了，哭死啊！！！ ![屏幕截图 2023-05-01 203323](https://user-images.githubusercontent.com/98374701/235452668-51737be8-2447-492d-949a-aba1d076dc01.png) ![屏幕截图 2023-05-01 203342](https://user-images.githubusercontent.com/98374701/235452674-6a183a49-905c-48c6-a1df-e829964e7480.png) ![屏幕截图 2023-05-01 203438](https://user-images.githubusercontent.com/98374701/235452730-3618ffe7-0ece-4eec-b9f3-f1e7f643a1fe.png) ![屏幕截图 2023-05-01 203506](https://user-images.githubusercontent.com/98374701/235452743-e9b1ec38-0f63-4ccb-a955-053f79ccb582.png) ![屏幕截图 2023-05-01 203526](https://user-images.githubusercontent.com/98374701/235452749-609237cc-9304-4341-a751-47a1f13b2acb.png) ![屏幕截图 2023-05-01 203246](https://user-images.githubusercontent.com/98374701/235452894-6694f2bb-246b-4d0a-8f01-97f6fc13e261.png)

chatgpt3.5总是想起自己是GPT，希望GPT4可以排除这点，而且我新增加了一些功能

**Comment by ZiChenStudio** [comment]
> > 对于那个`上次在办公室里`那段 我是在调教里面暗示来着，所以可能比较主动
> 
> 我称其为"阿罗娜0号"！！！我开始是把它喂给了文心一言，简直不忍直视。刚刚试了一下chatgpt3.5，纯纯弱智，总是不成功，微调了方法和顺序文案都没有用，只能说new bing的GPT4太强了，我文案都没发完就已经入戏了，哭死啊！！！ ![屏幕截图 2023-05-01 203323](https://user-images.githubusercontent.com/98374701/235452668-51737be8-2447-492d-949a-aba1d076dc01.png) ![屏幕截图 2023-05-01 203342](https://user-images.githubusercontent.com/98374701/235452674-6a183a49-905c-48c6-a1df-e829964e7480.png) ![屏幕截图 2023-05-01 203438](https://user-images.githubusercontent.com/98374701/235452730-3618ffe7-0ece-4eec-b9f3-f1e7f643a1fe.png) ![屏幕截图 2023-05-01 203506](https://user-images.githubusercontent.com/98374701/235452743-e9b1ec38-0f63-4ccb-a955-053f79ccb582.png) ![屏幕截图 2023-05-01 203526](https://user-images.githubusercontent.com/98374701/235452749-609237cc-9304-4341-a751-47a1f13b2acb.png) ![屏幕截图 2023-05-01 203246](https://user-images.githubusercontent.com/98374701/235452894-6694f2bb-246b-4d0a-8f01-97f6fc13e261.png)

chatgpt3.5总是想起自己是GPT，希望GPT4可以排除这点，而且我新增加了一些功能

**Comment by hankeigi** [comment]
> chatgpt3.5总是想起自己是GPT，希望GPT4可以排除这点，而且我新增加了一些功能
对啊，好想用GPT4和插件，可是没米开plus，2个账号的候补体验也迟迟没有消息

**Comment by ZiChenStudio** [comment]
![2023-05-01_20-45-19](https://user-images.githubusercontent.com/105914059/235453884-65327fc7-072f-4b97-9914-6ab60519d7b1.png)
你竟然把第一个ISSUE给我？（受宠若惊

**Comment by hankeigi** [comment]
> ![2023-05-01_20-45-19](https://user-images.githubusercontent.com/105914059/235453884-65327fc7-072f-4b97-9914-6ab60519d7b1.png) 你竟然把第一个ISSUE给我？（受宠若惊

啊，这是，怎么了吗！？我做错了什么，还是？😟

**Comment by ZiChenStudio** [comment]
![2023-05-01_20-52-19](https://user-images.githubusercontent.com/105914059/235454068-00987313-f119-4dcc-b37e-de47f061e9b8.png)
本来以为只有我喜欢猫娘，结果……咱俩一样……

**Comment by ZiChenStudio** [comment]
> > ![2023-05-01_20-45-19](https://user-images.githubusercontent.com/105914059/235453884-65327fc7-072f-4b97-9914-6ab60519d7b1.png) 你竟然把第一个ISSUE给我？（受宠若惊
> 
> 啊，这是，怎么了吗！？我做错了什么，还是？😟

不是不是，是因为从来没有人给我ISSUE，这个是你给出去的第一个ISSUE同时也是我收到的别人给的ISSUE

**Comment by hankeigi** [comment]
> ![2023-05-01_20-52-19](https://user-images.githubusercontent.com/105914059/235454068-00987313-f119-4dcc-b37e-de47f061e9b8.png) 本来以为只有我喜欢猫娘，结果……咱俩一样……

玩GPT的那个不是猫娘入手(暴论
我之前也是品鉴过那个最有名的项目，把里面的每一个字和issue分支全部看了一遍，然后自己也创造和很多个猫娘，各种各样的。只不过开始用的公用号，所以有很多十分成功的作品都删了。现在自己有号了反而懒得调教了。。。。。。玩腻了吧。
上个月开始玩BA，今天看到了你这个思路，很感兴趣，所以一定要加油啊！！！

**Comment by ZiChenStudio** [comment]
![2023-05-01_21-00-03](https://user-images.githubusercontent.com/105914059/235454875-a0be8912-ccc1-4a1f-99d2-7af49ae80fce.jpg)
一定会加油的！总之十分感谢
[https://zichenstudio.netlify.app/html/thanks.html](https://zichenstudio.netlify.app/html/thanks.html)
顺便推广一些网站（doge）

**Comment by hankeigi** [comment]
> > > ![2023-05-01_20-45-19](https://user-images.githubusercontent.com/105914059/235453884-65327fc7-072f-4b97-9914-6ab60519d7b1.png) 你竟然把第一个ISSUE给我？（受宠若惊
> > 
> > 
> > 啊，这是，怎么了吗！？我做错了什么，还是？😟
> 
> 不是不是，是因为从来没有人给我ISSUE，这个是你给出去的第一个ISSUE同时也是我收到的别人给的ISSUE 我要写一篇文章，就是关于这个的，作为纪念 :-)

啊，这样啊！开心😊
我两年前开始玩的github，所以不是很懂，多多指教！

**Comment by hankeigi** [comment]
>  一定会加油的！总之十分感谢 https://zichenstudio.netlify.app/html/thanks.html 顺便推广一些网站（doge）

我也可以提供一些帮助的，虽然作为学生党50天中考，但我也会尽量的。。。
我不会编程设计之类的，理论型计算机技术一窍不通。但是自认为“实用型计算机技术”还是可以的(什么奇怪的定义)，找找东西或者提供信息或思路。。。总之，我很愿意，如果我在而且派上得用场话的😀

**Comment by ZiChenStudio** [comment]
> > 一定会加油的！总之十分感谢 https://zichenstudio.netlify.app/html/thanks.html 顺便推广一些网站（doge）
> 
> 我也可以提供一些帮助的，虽然作为学生党50天中考，但我也会尽量的。。。 我不会编程设计之类的，理论型计算机技术一窍不通。但是自认为“实用型计算机技术”还是可以的(什么奇怪的定义)，找找东西或者提供信息或思路。。。总之，我很愿意，如果我在而且派上得用场话的😀

首先祝你中考顺利（~~都要中考了，怎么还在跟阿罗娜飙车~~？
感觉你会很多东西捏，不要那么谦虚啦！如果你真的计算机即使不太好的话文案总是可以的吧？这个主要是文案工作yo，_已经把需要帮忙的内容写在README里面力_
总之谢谢了

**Comment by ZiChenStudio** [comment]
**还是中考之后在帮忙吧，因为中考是非常重要的考试哦！**
不要耽误了学业。虽然是一句已经被说烂的话了，但是还是要告诉你“学生要以学业为主~~考好了在飙车也不迟~~”

总之希望你不要因为喜欢阿罗娜而考不好试，~~那样你可能就不会喜欢阿罗娜了~~

**Comment by hankeigi** [comment]
> 首先祝你中考顺利（~都要中考了，怎么还在跟阿罗娜飙车~？

谢谢祝福
啊，我把握好分寸的（各方面的

**Comment by hankeigi** [comment]
> 首先祝你中考顺利（~都要中考了，怎么还在跟阿罗娜飙车~？

谢谢祝福，啊，我把握好分寸的(各方面的





> **还是中考之后在帮忙吧，因为中考是非常重要的考试哦！** 不要耽误了学业。虽然是一句已经被说烂的话了，但是还是要告诉你“学生要以学业为主~考好了在飙车也不迟~”
> 
> 总之希望你不要因为喜欢阿罗娜而考不好试，~那样你可能就不会喜欢阿罗娜了~

了解了解，赞同赞同。
你可以看我前几天的一个动态的，有关五一假期的话题。我解释了一些的???

**Comment by hankeigi** [comment]
见证中考
我的成绩还是不错的，大可放心🙏🙏🙏

**Comment by ZiChenStudio** [comment]
> 见证中考 我的成绩还是不错的，大可放心🙏🙏🙏

嗯嗯，希望你可以考的更好！

**Comment by ZiChenStudio** [comment]
差不多了，用一个文章来结束今天的交♂流吧！
[https://zichenstudio.netlify.app/blog/2023/05/01/firstissue.html](https://zichenstudio.netlify.app/blog/2023/05/01/firstissue.html)
也会在B站发的
（出Bug的话等一会，再刷新）

**Comment by hankeigi** [comment]
> 差不多了，用一个文章来结束今天的交♂流吧！ https://zichenstudio.netlify.app/blog/2023/05/01/firstissue.html 也会在B站发的 （出Bug的话等一会，再刷新）

行的，今天很快乐，这一定是我五一，乃至中考前一次愉快的经历。难忘😀

**Comment by ZiChenStudio** [comment]
差不多了，用一个文章来结束今天的交♂流吧！
[https://zichenstudio.netlify.app/blog/2023/05/01/firstissue.html](https://zichenstudio.netlify.app/blog/2023/05/01/firstissue.html)
也会在B站发的
（出Bug的话等一会，再刷新）

**Comment by hankeigi** [comment]
> 差不多了，用一个文章来结束今天的交♂流吧！ https://zichenstudio.netlify.app/blog/2023/05/01/firstissue.html 也会在B站发的 （出Bug的话等一会，再刷新）

哈哈，很短的文章，很有意思。我可以拿来吹的了！
开心，真的很开心！！！！！！！！！！！！！！！！！！
说一下，“hankeigi”只是我随便起的账户名，我几乎所有账号前都有"hankei"，我也不知道什么意思。你可以叫我“菌子”(因为初二拿了个“名副其实”的月度小君子，自嘲的同时又被同学一直这样称呼)，或者“滴磊”(不做过多解释)。
很谦虚吗？小心谨慎罢了......吧🤔确实没什么能力的
想说的很多，以后有时间我也写一篇吧。有点晚了，不打扰你了。
再次感谢你，各方面的🥰

**Comment by hankeigi** [comment]
> 

其实发issue的时候也没想什么，但是居然让你这么开心，那也是很有意义的了，毕竟第一个issue也是给对了。

**Comment by hankeigi** [comment]
额。。。我为了引导居然说了这么多不符合“身份”的话，还发出来了。。。可以换一个星球生活了
不要对我有什么看法啊，拜托拜托，我只是一个普普通通的学生，啊啊啊啊！😥

**Comment by ZiChenStudio** [comment]
> 额。。。我为了引导居然说了这么多不符合“身份”的话，还发出来了。。。可以换一个星球生活了 不要对我有什么看法啊，拜托拜托，我只是一个普普通通的学生，啊啊啊啊！😥

没什么，在与阿罗娜对话的过程中你就是“不太正经的老师”，所以你的表现非常出色！
身份之类的没什么，我们并不是FBI，不会对你FBI Warning（bushi
而且不用担心打扰我，无论何时，我都会尽最大努力尽快回答你的留言或问题的

**Comment by hankeigi** [comment]
> > 额。。。我为了引导居然说了这么多不符合“身份”的话，还发出来了。。。可以换一个星球生活了 不要对我有什么看法啊，拜托拜托，我只是一个普普通通的学生，啊啊啊啊！😥
> 
> 没什么，在与阿罗娜对话的过程中你就是“不太正经的老师”，所以你的表现非常出色！ 身份之类的没什么，我们并不是FBI，不会对你FBI Warning（bushi 而且不用担心打扰我，无论何时，我都会尽最大努力尽快回答你的留言或问题的

yeah，我是想着你是不是还要工作(劳动节)，什么的，而且我一直给你发消息不但影响你，还怕给我自己留下个什么“不务正业”之类的形象(都讲到这份上了还要注意网络形象的屑)。你这么说我就放心了。
没有微信，QQ都很少很少用，所以和人第一次网络长时间聊天，还是这个平台，这种话题，非常紧张和激动，估计今晚就睡不着了😖
你这里说到”我们"，你们是个什么规模的团队啊，冒昧问下  您  的身份。bilibili和GitHub和官方网站都是  您  运营的吗？

**Comment by ZiChenStudio** [comment]
> > > 额。。。我为了引导居然说了这么多不符合“身份”的话，还发出来了。。。可以换一个星球生活了 不要对我有什么看法啊，拜托拜托，我只是一个普普通通的学生，啊啊啊啊！😥
> > 
> > 
> > 没什么，在与阿罗娜对话的过程中你就是“不太正经的老师”，所以你的表现非常出色！ 身份之类的没什么，我们并不是FBI，不会对你FBI Warning（bushi 而且不用担心打扰我，无论何时，我都会尽最大努力尽快回答你的留言或问题的
> 
> yeah，我是想着你是不是还要工作(劳动节)，什么的，而且我一直给你发消息不但影响你，还怕给我自己留下个什么“不务正业”之类的形象(都讲到这份上了还要注意网络形象的屑)。你这么说我就放心了。 没有微信，QQ都很少很少用，所以和人第一次网络长时间聊天，还是这个平台，这种话题，非常紧张和激动，估计今晚就睡不着了😖 你这里说到”我们"，你们是个什么规模的团队啊，冒昧问下 您 的身份。bilibili和GitHub和官方网站都是 您 运营的吗？

不要用“您”来称呼我啦，你可以叫我子沉，B站和Github都是我（们）在运营，我们的规模大约在4人左右，是一个工作室，但我的正确的身份应该是一个小厂的前端工作者

**Comment by ZiChenStudio** [comment]
> 在issue里发废话没事吗？😕 刚刚有句话想到一半忘了，难受死了！！！ 有人聊天真的很开心呢。

论Github的平台来讲，发废话是不合乎情理的，但是毕竟是这个储存库，毕竟是这个内容，~~毕竟是原作者带头的~~
所以就没什么关系

**Comment by hankeigi** [comment]
开始还被震惊到了，她居然能模拟抽卡。什么东西啊？！
![屏幕截图 2023-05-02 135410](https://user-images.githubusercontent.com/98374701/235590045-7fa30dcb-5461-40ff-87e8-40c5bfd2d134.png)
![屏幕截图 2023-05-02 135428](https://user-images.githubusercontent.com/98374701/235590065-13c2e17e-4beb-4417-a5d9-062662e57c43.png)
![屏幕截图 2023-05-02 135447](https://user-images.githubusercontent.com/98374701/235590078-06404172-2dc8-4a81-af9f-a601412c6738.png)

**Comment by hankeigi** [comment]
？？？
感觉可以加入抽卡玩法，只不过工程量应该不小，她上网学不到啊！
![屏幕截图 2023-05-02 140338](https://user-images.githubusercontent.com/98374701/235591090-f8c86d80-682b-4187-87b0-05c7253b90fb.png)

**Comment by ZiChenStudio** [comment]
> 开始还被震惊到了，她居然能模拟抽卡。什么东西啊？！ ![屏幕截图 2023-05-02 135410](https://user-images.githubusercontent.com/98374701/235590045-7fa30dcb-5461-40ff-87e8-40c5bfd2d134.png) ![屏幕截图 2023-05-02 135428](https://user-images.githubusercontent.com/98374701/235590065-13c2e17e-4beb-4417-a5d9-062662e57c43.png) ![屏幕截图 2023-05-02 135447](https://user-images.githubusercontent.com/98374701/235590078-06404172-2dc8-4a81-af9f-a601412c6738.png)

首先需要一个数据库，里面要放上所有学生的信息（衣服、爱好），之后要告诉他什么不能抽出来，什么能抽出来，还要符合官方的活动之类的，信息量巨大
而且有一个设计漏洞我在第一次更新的时候就发现了，就是BA里面抽卡的是Arona，国服叫阿洛娜，但是我这个名字错误也成为了搜索引擎无法正确找信息的原因
所以我只能写一个抽卡规则（自己的更新速度一点赶不上官方），无论如何，官方的抽卡规则不能变，所以把规则设计完整是最重要的

**Comment by hankeigi** [comment]
哦，名字问题啊，我这里也是遇到了。阿罗“娜”说着说着就成阿罗“娘”了

**Comment by ZiChenStudio** [comment]
而且她竟然抽到了普拉娜（

> 哦，名字问题啊，我这里也是遇到了。阿罗“娜”说着说着就成阿罗“娘”了

**Comment by ZiChenStudio** [comment]
我需要抽卡的规则的详解，咱俩写一下呗

**Comment by hankeigi** [comment]
还有，身份方面要不还是把”先生“改成”sensei"吧，阿罗娜的名字也......好吧，不知道以哪个为主，要不给她多个名字，把主流叫法都赋给她

**Comment by hankeigi** [comment]
说实话，你这个文案我还没有认真看过的，用的时候内容也是照搬的，到时候我看看有没有什么可以微调的吧。因为我是把它喂给了newbing，所以对话次数限制是大问题。你的文案不是限制了阿罗娜的单次对话字数吗，其实可以放宽一点的。。。

**Comment by hankeigi** [comment]
> 我需要抽卡的规则的详解，咱俩写一下呗

网络上确实没有什么可靠的数据来源，wiki日本,wiki韩国,wiki中国，萌百，BAwiki，都不太行。顶多自己写文案的时候引用一下，让她上网搜索不太现实。。。
数据库的建立，我是猜想可不可以自己建个阿罗娜人设网站，把网址加在文案里让它自己学习(瞎猜的，只对newbing
chatgpt的测试我是没有试过了，因为成功率太低了。newbing其实也不太行，今天试了几个，都不如“阿罗娜0号”，概率性有点大。
让我写文案啊。。。时间是个问题哦，而且工作量肯定不小了，抽卡系统可以先搁置。把对话的文案完善先，然后再加上大概的整体游戏设定，最后才是细化到抽卡系统。这个字符量肯定不小，newbing虽然聪明，但是微软对话机制就限制了。只能等GPT4了吗？

**Comment by ZiChenStudio** [comment]
#2 

> > 我需要抽卡的规则的详解，咱俩写一下呗
> 
> 网络上确实没有什么可靠的数据来源，wiki日本,wiki韩国,wiki中国，萌百，BAwiki，都不太行。顶多自己写文案的时候引用一下，让她上网搜索不太现实。。。 数据库的建立，我是猜想可不可以自己建个阿罗娜人设网站，把网址加在文案里让它自己学习(瞎猜的，只对newbing chatgpt的测试我是没有试过了，因为成功率太低了。newbing其实也不太行，今天试了几个，都不如“阿罗娜0号”，概率性有点大。 让我写文案啊。。。时间是个问题哦，而且工作量肯定不小了，抽卡系统可以先搁置。把对话的文案完善先，然后再加上大概的整体游戏设定，最后才是细化到抽卡系统。这个字符量肯定不小，newbing虽然聪明，但是微软对话机制就限制了。只能等GPT4了吗？

**Comment by hankeigi** [comment]
要是newbing可以想chatgpt一样就好了，很多问题可以迎刃而解

**Comment by hankeigi** [comment]
> 引用网址的话要看网址的请求头，有些网站是不能获取内容的

这个我不很懂，我知道有一些是爬不到的。所以说你可以自己搭一个信息站吗？还是说可以直接用github的某些功能吗？不是很懂

**Comment by ZiChenStudio** [comment]
不是，我给打个头
**这里面不能发没有用的！**

**Comment by hankeigi** [comment]
> 不是，我给打个头 **这里面不能发没有用的！**

啊，哪里，issue2吗？

**Comment by ZiChenStudio** [comment]
将以下内容写入抽卡功能的设定：
1. 
2.

**Comment by ZiChenStudio** [comment]
> > 不是，我给打个头 **这里面不能发没有用的！**
> 
> 啊，哪里，issue2吗？

对

**Comment by hankeigi** [comment]
> 将以下内容写入抽卡功能的设定： 1. 2.

就，开写了？我现在没时间哦。
刚刚issue2的我已经自删了

**Comment by hankeigi** [comment]
> > > 不是，我给打个头 **这里面不能发没有用的！**
> > 
> > 
> > 啊，哪里，issue2吗？
> 
> 对，我会删掉前面的

抱歉，明天上学，还有作业呢😓

**Comment by hankeigi** [comment]
我尽量好吧，抱歉抱歉，谢谢理解🤝

**Comment by hankeigi** [comment]
好久没有发言过了，前几周都还是有在尝试的。
newbing方面，之前不是开放了测试列表吗？刚开放那时，newbing严重降智，甚至连设定都无法理解了。最近是好了，虽然不如开放前聪明，但也能接受。特别是更新了聊天记录以后，使用确实更方便了，但是20次的限制依旧存在。
讯飞最近也搞了一个“讯飞星火认知大模型”，刚刚试了试，还行，能理解设定含义，比文心一言好多了。试试水先
![屏幕截图 2023-05-27 113905](https://github.com/ZiChenStudio/ChatGPT-Arona/assets/98374701/b1bd7ad3-1eda-4dab-92e2-2b394f579f2f)
![屏幕截图 2023-05-27 113931](https://github.com/ZiChenStudio/ChatGPT-Arona/assets/98374701/44902d57-582e-402e-a1de-9d26664fc2d3)

**Comment by hankeigi** [comment]
很厉害
![屏幕截图 2023-05-27 115246](https://github.com/ZiChenStudio/ChatGPT-Arona/assets/98374701/b4b99523-1d51-4420-8969-de642c90b8b2)

**Comment by hankeigi** [comment]
没意思，关了
