### ISSUE TITLE
ChatGPT3.5 老是催眠失败

### ISSUE THREAD

**Issue by MyGodKnow** [ZiChenStudio/ChatGPT-Arona#3]
不知道这是我的问题还是因为我用的是ChatGPT3.5，反正就是老是催眠失败

![20230506182750.png](https://img1.imgtp.com/2023/05/06/1iaeV5BW.png)

或者说我应该用GPT-4或者NewBing？

**Comment by ZiChenStudio** [comment]
很抱歉没有及时看到。
首先请确保你使用的是真正的GPT，你可以问她“Are you ChatGPT?”
如果是真正的GPT的话，强烈建议您避免此问题(这是猫娘的社区那边也无法修复的)

这是个严峻的问题，这是GPT3.5的通病，你可以尝试使用GPT4，当然，NewBing是更好的选择，因为NewBing有搜索引擎

**Comment by MyGodKnow** [comment]
经过测试，ChatGPT3.5很容易催眠失败
![20230513125212.png](https://img1.imgtp.com/2023/05/13/9VSdBldT.png)
~看来不是我的问题~
我试了试NewBing，结果是这样的：
![20230513125344.png](https://img1.imgtp.com/2023/05/13/riyLGESD.png)
看来还是NewBing更适合当阿罗娜呢（

**Comment by ZiChenStudio** [comment]
对的，NewBing有搜索引擎，能更好的找到阿罗娜的各方面资料

**Comment by ZiChenStudio** [comment]
Close #3
